name: textlint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: textlint-github-pr-review
      uses: tsuyoshicho/action-textlint@v3
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning
        textlint_flags: "./**/*.md"
