name: textlint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Install textlint and preset-japanese
      run: npm install textlint textlint-rule-preset-japanese

    - name: Create .textlintrc
      run: |
        echo '{
          "rules": {
            "preset-japanese": true
          }
        }' > .textlintrc

    - name: Run textlint
      run: |
        npx textlint -f checkstyle "**/*.md" > .textlint.log

    - name: Report results with reviewdog
      if: failure()
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat .textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review -level=warning

